name: Deploy to Prod Environment

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter infra...

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActionsProdDeploy

      - name: CDK Deploy to Prod
        run: |
          STACK_SUFFIX="-prod"
          pnpm --filter infra cdk deploy "*${STACK_SUFFIX}" \
            -c environment=prod \
            --require-approval never \
            --outputs-file cdk-outputs-prod.json
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          PROD_DOMAIN_NAME: ${{ secrets.PROD_DOMAIN_NAME }}
          PROD_HOSTED_ZONE_ID: ${{ secrets.PROD_HOSTED_ZONE_ID }}
          PROD_ALLOWED_EMAIL_DOMAINS: ${{ secrets.PROD_ALLOWED_EMAIL_DOMAINS }}
